### ISSUE TITLE
initialized(...) does not compile with gcc

### ISSUE THREAD

**Issue by heather7283** [JacksonAllan/CC#29]
Attempting to use initialized(...) macro with gcc results in compiler error.

For example, compiling this code (test.c):
```c
#include "cc.h"

list(int) list_of_foo = initialized(&list_of_foo);

int main(int argc, char **argv) {
    /* ... */
}
```
with
```
gcc test.c -o test
```
results in the following:
```
In file included from test.c:1:
cc.h:6439:1: error: initializer element is not constant
 6439 | (                                                                                    \
      | ^
cc.h:1308:30: note: in definition of macro 'CC_MSVC_PP_FIX'
 1308 | #define CC_MSVC_PP_FIX( xp ) xp
      |                              ^~
cc.h:1129:47: note: in expansion of macro 'cc_initialized'
 1129 | #define initialized( ... )    CC_MSVC_PP_FIX( cc_initialized( __VA_ARGS__ ) )
      |                                               ^~~~~~~~~~~~~~
test.c:3:25: note: in expansion of macro 'initialized'
    3 | list(int) list_of_foo = initialized(&list_of_foo);
      |                         ^~~~~~~~~~~
```

EDIT: Seems to work fine in 006960a99ee622f4ae5e8eb692668cda5b4fd344, but got broken in 6fbe0f44437f9292a37b91987cbd52ef4dab2b90.

**Comment by JacksonAllan** [comment]
This should now be fixed by [v1.4.3](https://github.com/JacksonAllan/CC/releases/tag/v1.4.3).

The fixed involved removing the `CC_STATIC_ASSERT` type check from `cc_initialized`, as shown in my previous response. I also added the check back into `cc_init` (which itself invokes `cc_initialized`). In either case, the check is mostly unnecessary anyway. These macros will almost always fail to compile if supplied an argument that is not a pointer to a CC container. The check is more useful in API macros that accept certain containers but not others.

Please just let me know if you run into any other issues :)

**Comment by heather7283** [comment]
Thank you!
